import CoreData

// MARK: - Managed objects

/// The hot half of an item: everything the panel needs to draw a card, filter it and dedup it,
/// and nothing else.
///
/// The split is the whole point of this schema. Drawing the history means materialising every row
/// in it, and Core Data materialises a row's attributes together — so anything living here is
/// something the app pays for on every item it shows, whether or not a user ever looks at that
/// item. The payload is the other half, in `ItemDataEntity`, behind a fault.
@objc(ItemEntity)
final class ItemEntity: NSManagedObject {
    @NSManaged var id: UUID
    @NSManaged var typeName: String
    @NSManaged var timestamp: Date
    @NSManaged var isPinned: Bool
    @NSManaged var label: String?

    /// Dedup key. Indexed, so "have I already got this?" is a lookup rather than a walk over the
    /// history comparing strings — which is what it was when items lived in an array.
    @NSManaged var checksum: String

    /// The text a card shows and the search box matches, capped at `ItemEntity.previewCharLimit`.
    ///
    /// The full text is in the payload. Keeping all of it here would put a pasted log file into
    /// memory for as long as the app runs, and neither a card nor a search result can show more
    /// than the first few hundred characters anyway.
    @NSManaged var previewText: String?

    /// Length of the full text, so a card can say it is showing part of something larger without
    /// reading the payload to find out.
    @NSManaged var fullTextLength: Int64

    @NSManaged var ocrText: String?
    @NSManaged var revision: Int32
    @NSManaged var imageHash: String?
    @NSManaged var imageSize: Int64

    /// File and folder paths, as a binary plist of strings. Hot because a file card shows them and
    /// dedup compares them — small, and there is no card that does not need them.
    @NSManaged var rawFilePaths: Data?

    /// Pasteboard type of the formatted representation, and whether there is one. Hot because the
    /// card decides *whether* to render rich text before it decides to load any: without these two
    /// it would have to fault in every payload in the history to find out which ones have styling.
    @NSManaged var richTypeName: String?
    @NSManaged var hasRichText: Bool

    /// Size of the stored payload, for accounting that must not fault it in.
    @NSManaged var payloadBytes: Int64

    @NSManaged var data: ItemDataEntity?
    @NSManaged var sourceApplication: ApplicationEntity?

    /// Where `previewText` is cut.
    ///
    /// Generous next to what a card draws (a dozen lines) because the same string is what search
    /// matches against, and a match the user can see in the panel but not find by typing is worse
    /// than a card that shows a little more than it needs.
    static let previewCharLimit = 4096
}

/// The cold half: every representation the source app offered, exactly as it offered them.
///
/// One attribute in an entity of its own rather than a column on `ItemEntity`, because that is what
/// makes it a fault. `allowsExternalBinaryDataStorage` then keeps the large ones out of the
/// database file itself — verified: a 2 MB blob lands in `_EXTERNAL_DATA`, a 100 byte one stays
/// inline.
@objc(ItemDataEntity)
final class ItemDataEntity: NSManagedObject {
    @NSManaged var rawPasteboardItems: Data?
    @NSManaged var item: ItemEntity?
}

/// The app an item was copied from, stored once instead of once per item.
///
/// Deliberately without Paste's icon blob. Icons come from `AppNameResolver`, which reads them from
/// the installed app: that keeps the database from carrying a copy of every icon in the history,
/// and an app that changes its icon changes it here too.
@objc(ApplicationEntity)
final class ApplicationEntity: NSManagedObject {
    @NSManaged var bundleIdentifier: String
    @NSManaged var name: String?
    @NSManaged var createdAt: Date
    @NSManaged var items: NSSet?
}

// MARK: - Model

/// The managed object model, built in code.
///
/// In code rather than in a `.xcdatamodeld` because the project is generated by xcodegen and a
/// model bundle is one more thing that has to be wired into it and kept in step by hand — and
/// because everything a model file can express that this schema needs, including
/// `allowsExternalBinaryDataStorage`, is settable here and verifiable in a test.
enum ClipboardSchema {

    /// Built once for the process.
    ///
    /// `NSManagedObject` subclasses resolve their entity through `+entity`, which searches every
    /// model that has been loaded — so a second model describing the same class names makes that
    /// lookup ambiguous, and Core Data says so: "Multiple NSEntityDescriptions claim the
    /// NSManagedObject subclass 'ItemEntity'". One store per process is the normal case and would
    /// never have shown it; the tests open several, which is what surfaced it.
    static let model: NSManagedObjectModel = makeModel()

    static func makeModel() -> NSManagedObjectModel {
        let model = NSManagedObjectModel()

        let item = NSEntityDescription()
        item.name = "ItemEntity"
        item.managedObjectClassName = NSStringFromClass(ItemEntity.self)

        let payload = NSEntityDescription()
        payload.name = "ItemDataEntity"
        payload.managedObjectClassName = NSStringFromClass(ItemDataEntity.self)

        let app = NSEntityDescription()
        app.name = "ApplicationEntity"
        app.managedObjectClassName = NSStringFromClass(ApplicationEntity.self)

        item.properties = [
            attribute("id", .UUIDAttributeType, optional: false),
            attribute("typeName", .stringAttributeType, optional: false, default: "text"),
            attribute("timestamp", .dateAttributeType, optional: false, default: Date(timeIntervalSince1970: 0)),
            attribute("isPinned", .booleanAttributeType, optional: false, default: false),
            attribute("label", .stringAttributeType),
            attribute("checksum", .stringAttributeType, optional: false, default: ""),
            attribute("previewText", .stringAttributeType),
            attribute("fullTextLength", .integer64AttributeType, optional: false, default: 0),
            attribute("ocrText", .stringAttributeType),
            attribute("revision", .integer32AttributeType, optional: false, default: 0),
            attribute("imageHash", .stringAttributeType),
            attribute("imageSize", .integer64AttributeType, optional: false, default: 0),
            attribute("rawFilePaths", .binaryDataAttributeType),
            attribute("richTypeName", .stringAttributeType),
            attribute("hasRichText", .booleanAttributeType, optional: false, default: false),
            attribute("payloadBytes", .integer64AttributeType, optional: false, default: 0),
        ]

        let rawPayload = attribute("rawPasteboardItems", .binaryDataAttributeType)
        // The reason this entity exists — see `ItemDataEntity`.
        rawPayload.allowsExternalBinaryDataStorage = true
        payload.properties = [rawPayload]

        app.properties = [
            attribute("bundleIdentifier", .stringAttributeType, optional: false, default: ""),
            attribute("name", .stringAttributeType),
            attribute("createdAt", .dateAttributeType, optional: false, default: Date(timeIntervalSince1970: 0)),
        ]

        // Deleting an item takes its payload with it: nothing else can ever reach that row, so a
        // payload outliving its item is unreachable bytes on disk and nothing else.
        let itemToData = relationship("data", to: payload, toMany: false, rule: .cascadeDeleteRule)
        let dataToItem = relationship("item", to: item, toMany: false, rule: .nullifyDeleteRule)
        itemToData.inverseRelationship = dataToItem
        dataToItem.inverseRelationship = itemToData

        // An app row outlives the items copied from it — it is shared, and clearing the history
        // must not have to decide which rows are still referenced.
        let itemToApp = relationship("sourceApplication", to: app, toMany: false, rule: .nullifyDeleteRule)
        let appToItems = relationship("items", to: item, toMany: true, rule: .nullifyDeleteRule)
        itemToApp.inverseRelationship = appToItems
        appToItems.inverseRelationship = itemToApp

        item.properties.append(contentsOf: [itemToData, itemToApp])
        payload.properties.append(dataToItem)
        app.properties.append(appToItems)

        // Uniqueness enforced by the store rather than by the code that writes to it: an id that
        // arrives twice is a bug, and one that silently produced two rows would show up as a
        // duplicate card long after the write that caused it.
        item.uniquenessConstraints = [["id"]]
        app.uniquenessConstraints = [["bundleIdentifier"]]

        item.indexes = [
            index("byTimestamp", on: item, properties: ["timestamp"]),
            index("byChecksum", on: item, properties: ["checksum"]),
            index("byPinnedAndTimestamp", on: item, properties: ["isPinned", "timestamp"]),
        ]
        app.indexes = [index("byBundleIdentifier", on: app, properties: ["bundleIdentifier"])]

        model.entities = [item, payload, app]
        return model
    }

    // MARK: - Builders

    private static func attribute(_ name: String,
                                  _ type: NSAttributeType,
                                  optional: Bool = true,
                                  default value: Any? = nil) -> NSAttributeDescription {
        let attr = NSAttributeDescription()
        attr.name = name
        attr.attributeType = type
        attr.isOptional = optional
        attr.defaultValue = value
        return attr
    }

    private static func relationship(_ name: String,
                                     to destination: NSEntityDescription,
                                     toMany: Bool,
                                     rule: NSDeleteRule) -> NSRelationshipDescription {
        let rel = NSRelationshipDescription()
        rel.name = name
        rel.destinationEntity = destination
        rel.minCount = 0
        rel.maxCount = toMany ? 0 : 1
        rel.deleteRule = rule
        rel.isOptional = true
        return rel
    }

    private static func index(_ name: String,
                              on entity: NSEntityDescription,
                              properties: [String]) -> NSFetchIndexDescription {
        let elements = properties.compactMap { propertyName -> NSFetchIndexElementDescription? in
            guard let property = entity.properties.first(where: { $0.name == propertyName }) else {
                return nil
            }
            return NSFetchIndexElementDescription(property: property, collationType: .binary)
        }
        return NSFetchIndexDescription(name: name, elements: elements)
    }
}
