import AppKit
import UniformTypeIdentifiers

/// Every representation the source app put on the pasteboard, kept as the bytes it handed over.
///
/// ## Why all of them
///
/// Capture used to keep one formatted representation — RTF, or HTML when there was no RTF — plus
/// the plain string, and dropped the rest. That is lossless only for content whose formatting fits
/// in RTF. A table copied out of Excel, a shape copied out of Figma and a file copied out of Finder
/// each carry app-specific types alongside the public ones, and a paste that has only the public
/// ones back is a paste of something simpler than what was copied.
///
/// ## What this cannot fix
///
/// Fidelity here is fidelity *to the pasteboard*, which is not the same as fidelity to what the
/// user was looking at. Cocoa's RTF writer cannot name the system face, so text copied out of an
/// AppKit app arrives with `HelveticaNeue` already written into its font table — measured, and
/// byte-identical to what genuine Helvetica Neue produces, in every representation the source
/// offers. Keeping those bytes verbatim keeps the substitution verbatim too. `SystemFontRTF` is
/// where that is dealt with; storage cannot reach it.
struct PasteboardPayload: Equatable {

    /// One `NSPasteboardItem`'s worth of representations.
    ///
    /// `types` keeps the source's own order, which is its declared preference order. Replaying it
    /// unchanged is what lets a receiving app pick the representation it would have picked had it
    /// been handed the original copy.
    struct Item: Equatable {
        var types: [String]
        var dataByType: [String: Data]

        func data(forType type: String) -> Data? { dataByType[type] }
    }

    var items: [Item]

    var isEmpty: Bool { items.allSatisfy { $0.types.isEmpty } }

    /// Total stored bytes, counting a blob shared by several types once.
    var byteCount: Int {
        var seen: [BlobKey: Data] = [:]
        for item in items {
            for data in item.dataByType.values { seen[BlobKey(data), default: data] = data }
        }
        return seen.values.reduce(0) { $0 + $1.count }
    }

    // MARK: - Limits

    /// What capture refuses to take on.
    ///
    /// A cap is not a size the format cannot express — it is a decision that one clipboard entry is
    /// not worth an unbounded amount of the user's disk. The history holds up to 3000 items, so
    /// anything allowed here is allowed three thousand times over.
    struct Limits: Equatable {
        /// The largest single representation worth keeping. Sized to hold a full-resolution
        /// screenshot PNG, which is the largest thing people copy routinely.
        var perRepresentation: Int
        /// The ceiling for one clipboard entry across all its representations.
        var total: Int

        static let `default` = Limits(perRepresentation: 8 * 1024 * 1024,
                                      total: 24 * 1024 * 1024)
    }

    /// Types never worth storing, whatever their size.
    ///
    /// Kept short on purpose. Every entry here is a representation this app would rather not have,
    /// and the cost of guessing wrong is silent loss of fidelity — the exact failure the payload
    /// exists to end. A type is listed only when keeping it is provably pointless.
    private static let excludedTypes: Set<String> = [
        // An icon for something the payload already names by path — rebuildable from the file
        // itself, and measured at 251 KB for one folder copied out of Finder, which was larger
        // than every other representation of that item put together.
        "com.apple.icns",
        // Advisory hints about how the copy should be treated (nspasteboard.com). `ClipboardMonitor`
        // reads them at capture time to decide whether the item is stored at all; past that
        // decision they describe the copy, not the content.
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.source",
    ]

    /// Promises rather than content: they name bytes the source app produces on demand, and the
    /// promise dies with the copy that made it. Stored, they are a reference that can never be
    /// fulfilled again — worse than absent, because a reader would try.
    private static let excludedPrefixes = ["com.apple.pasteboard.promised-"]

    static func isStorable(_ type: String) -> Bool {
        !excludedTypes.contains(type) && !excludedPrefixes.contains { type.hasPrefix($0) }
    }

    // MARK: - Capture

    /// Reads everything storable off `pb`, newest-first order preserved, or nil when nothing
    /// survived the filters.
    ///
    /// Representations are taken in the source's order and dropped from the end once `limits.total`
    /// is reached, so what gets cut is what the source ranked lowest.
    static func capture(from pb: NSPasteboard, limits: Limits = .default) -> PasteboardPayload? {
        guard let pbItems = pb.pasteboardItems else { return nil }

        var blobs = BlobTable()
        var captured: [Item] = []
        var total = 0

        for pbItem in pbItems {
            var types: [String] = []
            var dataByType: [String: Data] = [:]

            for type in pbItem.types {
                let raw = type.rawValue
                guard isStorable(raw) else { continue }
                guard let data = pbItem.data(forType: type), !data.isEmpty else { continue }
                guard data.count <= limits.perRepresentation else { continue }

                // Shared blobs are counted and stored once.
                //
                // Not for AppKit's legacy aliases, which never get this far: a rich-text copy shows
                // six types on `pb.types` — `public.rtf` and the NeXT name, and both plain-text
                // flavours twice — but `pasteboardItems` reports the canonical three, measured, and
                // AppKit re-derives the aliases from them on the way back out. This is for the case
                // that remains: an app offering the same bytes under a public type and a private
                // one of its own. It costs a length comparison when it does not fire.
                let shared: Data
                if let held = blobs.stored(data) {
                    shared = held
                } else {
                    guard total + data.count <= limits.total else { continue }
                    total += data.count
                    shared = blobs.intern(data)
                }

                types.append(raw)
                dataByType[raw] = shared
            }

            if !types.isEmpty { captured.append(Item(types: types, dataByType: dataByType)) }
        }

        guard !captured.isEmpty else { return nil }
        return PasteboardPayload(items: captured)
    }

    // MARK: - Replay

    /// Writes every stored representation back, in the order it was captured.
    ///
    /// `clearContents` is the caller's job: writing an item is one half of a paste, and the other
    /// half — claiming the change as xPaste's own — has to bracket it. See `ClipboardItem.write`.
    func write(to pb: NSPasteboard) {
        guard !items.isEmpty else { return }
        let objects = items.map { item -> NSPasteboardItem in
            let pbItem = NSPasteboardItem()
            for type in item.types {
                guard let data = item.dataByType[type] else { continue }
                pbItem.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            return pbItem
        }
        pb.writeObjects(objects)
    }

    // MARK: - Reading

    /// The first item's bytes for `type`, which is what every caller outside a multi-item paste
    /// wants: a copy of several things at once is rare, and none of the readers below mean
    /// "the second one".
    func data(forType type: String) -> Data? { items.first?.data(forType: type) }

    func data(forType type: NSPasteboard.PasteboardType) -> Data? { data(forType: type.rawValue) }

    /// The plain string, from whichever encoding the source offered.
    var string: String? {
        if let d = data(forType: .string), let s = String(data: d, encoding: .utf8) { return s }
        if let d = data(forType: "public.utf8-plain-text"),
           let s = String(data: d, encoding: .utf8) { return s }
        if let d = data(forType: "public.utf16-external-plain-text"),
           let s = String(data: d, encoding: .utf16) { return s }
        return nil
    }

    /// The picture as the source app offered it, and the type it offered it under.
    ///
    /// PNG first, then TIFF, then JPEG: the first two are lossless and the third is what is left.
    /// After those, anything the system agrees is an image — an app offering only HEIC should not
    /// come back empty just because this list did not name it.
    ///
    /// Which type is chosen matters less than it looks: every reader of this sniffs the bytes for
    /// their real format rather than trusting a name — see `SaveFormat.recognisedImageExtension`.
    var imageRepresentation: (data: Data, type: String)? {
        for candidate in ["public.png", "public.tiff", "public.jpeg"] {
            if let data = data(forType: candidate), !data.isEmpty { return (data, candidate) }
        }
        for type in items.first?.types ?? [] {
            guard let utType = UTType(type), utType.conforms(to: .image),
                  let data = data(forType: type), !data.isEmpty else { continue }
            return (data, type)
        }
        return nil
    }

    /// Replaces the plain and formatted representations with what came out of the editor, leaving
    /// every other representation alone.
    ///
    /// An edit changes the text, not what kind of thing the item is, so an app-specific type that
    /// described the original still describes it. Dropping those on the first edit would make
    /// editing a way to silently downgrade an item — which is what the payload exists to prevent.
    /// The types that *did* change are rewritten; the ones that cannot be regenerated are dropped
    /// rather than left stale.
    func replacingText(_ text: String, rich: (data: Data, type: String)?) -> PasteboardPayload {
        var item = items.first ?? Item(types: [], dataByType: [:])

        let stale = [NSPasteboard.PasteboardType.rtf.rawValue,
                     NSPasteboard.PasteboardType.html.rawValue,
                     NSPasteboard.PasteboardType.string.rawValue,
                     "public.utf8-plain-text",
                     "public.utf16-external-plain-text",
                     "NeXT Rich Text Format v1.0 pasteboard type",
                     "NSStringPboardType",
                     "CorePasteboardFlavorType 0x75743136"]
        item.types.removeAll { stale.contains($0) }
        for type in stale { item.dataByType.removeValue(forKey: type) }

        var rebuilt: [String] = []
        if let rich {
            item.dataByType[rich.type] = rich.data
            rebuilt.append(rich.type)
        }
        item.dataByType[NSPasteboard.PasteboardType.string.rawValue] = Data(text.utf8)
        rebuilt.append(NSPasteboard.PasteboardType.string.rawValue)

        // Rebuilt types go first: they are the ones that now describe the item, and the order is
        // the preference order a reader honours.
        item.types = rebuilt + item.types
        return PasteboardPayload(items: [item] + items.dropFirst())
    }

    /// A payload holding nothing but a plain string, for items that never had one — anything
    /// restored from the pre-payload JSON history, and anything built in a test.
    static func plainText(_ text: String) -> PasteboardPayload {
        PasteboardPayload(items: [Item(types: [NSPasteboard.PasteboardType.string.rawValue],
                                       dataByType: [NSPasteboard.PasteboardType.string.rawValue:
                                                        Data(text.utf8)])])
    }
}
