import AppKit

final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    private init() {}

    static let defaultInterval: TimeInterval = 0.1
    private var interval: TimeInterval {
        let v = UserDefaults.standard.double(forKey: "clipboardScanInterval")
        return v > 0 ? v : Self.defaultInterval
    }

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func restart() {
        stop()
        start()
    }

    func markNextChangeAsOwn() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    // De-facto standard pasteboard hints (nspasteboard.com) set by password managers and
    // apps that generate throwaway content.
    private static let concealedType = "org.nspasteboard.ConcealedType"
    private static let transientTypes = ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let sourceBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        // Privacy filters.
        let defaults = UserDefaults.standard
        if let bid = sourceBundleID,
           let ignored = defaults.stringArray(forKey: "ignoredAppBundleIDs"),
           ignored.contains(bid) {
            return
        }
        let types = (pb.types ?? []).map(\.rawValue)
        if defaults.bool(forKey: "ignoreConfidentialContent"),
           types.contains(Self.concealedType) {
            return
        }
        if defaults.bool(forKey: "ignoreTransientContent"),
           types.contains(where: { Self.transientTypes.contains($0) }) {
            return
        }

        let hasFileURLs = (pb.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL])?.isEmpty == false

        if !hasFileURLs,
           let types = pb.types,
           types.contains(where: { $0 == .tiff || $0 == .png }),
           let image = NSImage(pasteboard: pb) {
            Task.detached(priority: .userInitiated) {
                guard let compressed = image.compressedJPEGData(maxBytes: 1_000_000) else { return }
                var item = ClipboardItem(type: .image, imageData: compressed)
                item.sourceAppBundleID = sourceBundleID
                await MainActor.run { ClipboardStore.shared.add(item) }
            }
            return
        }

        guard var item = ClipboardItem.from(pasteboard: pb) else { return }
        item.sourceAppBundleID = sourceBundleID
        DispatchQueue.main.async {
            ClipboardStore.shared.add(item)
        }
    }
}
