import AppKit

final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount: Int

    /// The board this monitor watches. Injectable so the "this change is ours" handshake can be
    /// exercised on a scratch pasteboard rather than on the user's real clipboard.
    private let pasteboard: NSPasteboard

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    static let defaultInterval: TimeInterval = 0.1
    private var interval: TimeInterval {
        let v = UserDefaults.standard.double(forKey: "clipboardScanInterval")
        return v > 0 ? v : Self.defaultInterval
    }

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func restart() {
        stop()
        start()
    }

    func markNextChangeAsOwn() {
        lastChangeCount = pasteboard.changeCount
    }

    /// Whether what is on the pasteboard right now has been claimed as xPaste's own — i.e. the
    /// next poll passes over it instead of capturing it as a new item.
    var ownsCurrentChange: Bool { pasteboard.changeCount == lastChangeCount }

    /// Writes to the pasteboard and claims the change, in that order.
    ///
    /// The order is the whole point. `markNextChangeAsOwn` records the count *as it stands*, so
    /// claiming before writing claims the change that came before xPaste's own — and the write
    /// that follows is then captured right back into the history, filed under whichever app
    /// happened to be frontmost, replacing the item it was pasted from.
    func writeOwned(_ write: (NSPasteboard) -> Void) {
        write(pasteboard)
        markNextChangeAsOwn()
    }

    // De-facto standard pasteboard hints (nspasteboard.com) set by password managers and
    // apps that generate throwaway content.
    private static let concealedType = "org.nspasteboard.ConcealedType"
    private static let transientTypes = ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]

    private func poll() {
        let pb = pasteboard
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let sourceBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        // Privacy filters.
        let defaults = UserDefaults.standard
        if let bid = sourceBundleID,
           let ignored = defaults.stringArray(forKey: "ignoredAppBundleIDs"),
           ignored.contains(bid) {
            return
        }
        let types = (pb.types ?? []).map(\.rawValue)
        if defaults.bool(forKey: "ignoreConfidentialContent"),
           types.contains(Self.concealedType) {
            return
        }
        if defaults.bool(forKey: "ignoreTransientContent"),
           types.contains(where: { Self.transientTypes.contains($0) }) {
            return
        }

        let hasFileURLs = (pb.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL])?.isEmpty == false

        if !hasFileURLs,
           let types = pb.types,
           types.contains(where: { $0 == .tiff || $0 == .png }),
           let image = NSImage(pasteboard: pb) {
            Task.detached(priority: .userInitiated) {
                guard let compressed = image.compressedData(maxBytes: 1_000_000) else { return }
                var item = ClipboardItem(type: .image, imageData: compressed)
                item.sourceAppBundleID = sourceBundleID
                await MainActor.run { ClipboardStore.shared.add(item) }
                OCRService.scan(itemID: item.id, imageData: compressed)
            }
            return
        }

        guard var item = ClipboardItem.from(pasteboard: pb) else { return }

        // Never-store patterns (tokens, keys, card numbers). Checked against the text and, for
        // file items, the paths — the point is that this content never reaches disk at all.
        let patterns = ExclusionRules.storedPatterns(defaults)
        if !patterns.isEmpty {
            let candidates = [item.text, item.fileURLs?.map(\.path).joined(separator: "\n")]
            if candidates.compactMap({ $0 }).contains(where: {
                ExclusionRules.shouldExclude($0, patterns: patterns)
            }) {
                return
            }
        }

        item.sourceAppBundleID = sourceBundleID
        DispatchQueue.main.async {
            ClipboardStore.shared.add(item)
        }
    }
}
